[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable compiler optimization (reduces gas usage)
optimizer = true
optimizer_runs = 200

# Test configuration
ffi = false                # Disable external script calls (for security)
gas_reports = ["*"]        # Generate gas usage reports
verbosity = 2              # Log output level


# Allow calling private functions (for debugging)
via_ir = false

# Cache compilation results to speed up subsequent builds
cache = true


# Default account balance for coverage testing (1,000 ETH) Anvil only
eth_balance = "1000000000000000000000"


[rpc_endpoints]
local = "http://127.0.0.1:8545" # Anvil Environment
# Ethereum Testnet
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
# Or using Alchemy
# sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# See more configuration options: https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
